# Site configuration
tagline: "[<strong>code</strong>crate] <span class='text-primary'>Building better</text-primary> <strong>code</strong>"
title: "[codecrate] Building better code"
# customize the post url to include date + title to mirror existing blogger urls
# ex: /2009-04-29-slap-chop.textile
permalink: /:year/:month/:title.html
search: true
# The url is only used when full-domain names are needed
# such as sitemap and atom
# Most places will/should use BASE_PATH to make the urls
url: http://codecrate.com

# Site owner/author info
owner:
  name: Ryan Sonnek
  avatar: avatar.jpg
  email: ryan@codecrate.com
  twitter: codecrate
  github: wireframe
  linkedin: ryansonnek
  disqus-shortname: ryansonnek
  google:
    analytics: 'UA-1922195-6'

author:
  bio: "A passionate web developer focused on launching Lean startups using Ruby and Javascript technologies."

# Jekyll Configuration
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
markdown: redcarpet
exclude:
  - README.md
  - CNAME
  - params.json
gems:
  - jekyll-sitemap

