# customize the post url to include date + title
# ex: /2009-04-29-slap-chop.textile
permalink: /:year/:month/:day/:title.html

exclude:
  - README.md
  - CNAME
  - params.json

# Settings for analytics helper
analytics :
  provider : google
  google :
      tracking_id : 'TODO'

markdown: redcarpet