# customize the post url to include date + title
# ex: /2009-04-29-slap-chop.textile
permalink: /:year/:month/:day/:title.html

exclude:
  - README.md
  - CNAME
  - params.json

# Settings for analytics helper
analytics :
  tracking_id : 'UA-1922195-6'

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
production_url : http://codecrate.com

markdown: redcarpet