# customize the post url to include date + title to mirror existing blogger urls
# ex: /2009-04-29-slap-chop.textile
permalink: /:year/:month/:day/:title.html

exclude:
  - README.md
  - CNAME
  - params.json

# Settings for analytics helper
analytics :
  tracking_id : 'UA-1922195-6'

# The url is only used when full-domain names are needed
# such as sitemap and atom
# Most places will/should use BASE_PATH to make the urls
url: http://codecrate.com

# general author info
author:
  name: Ryan Sonnek
  email: ryan@codecrate.com

markdown: redcarpet