name: Check links

on:
  pull_request:
  workflow_dispatch:

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          # html-proofer's async dependency requires Ruby >= 3.3
          ruby-version: '3.3'
          bundler-cache: true
      - name: Check internal links and images
        run: bin/check-links
