name: Check links

on:
  pull_request:
  workflow_dispatch:

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: Install gems
        run: bundle install
      - name: Check internal links and images
        run: bin/check-links
